### PR TITLE
GridContainer Flatlist Implementation

### PR DESCRIPTION
**Pull request by iRoachie**
Using a ListView, thumbnails start to drop out once more than 50+ items are in the gallery. This is the first attempt at transitioning to FlatList - a more performant list view. 

Need your feedback on it.

### CODE REVIEW

**Comment by halilb** [comment]
Awesome @iRoachie!

It seems we had an easy transition. Did you notice any problems with this?

I'll try it on my device when I have some free time.

**Comment by iRoachie** [comment]
No problems as yet. Right now I tested it on android 4.4.2 and it seems to be working okay

**Comment by ngandhy** [comment]
@iRoachie @halilb 

was this ever merged in?

**Comment by iRoachie** [comment]
It wasn't

**Pull request closed without merging**
