### PR TITLE
Minor fix and Zoom capabilities of images

### PR DESCRIPTION
**Pull request by akki-ng**
The issues have been fix and tested well on android. An example "PhotoBrowserExampleZoom" has been added for demonstration. Tested on iOS as well but could see the loading image only. Please confirm if there is an issue with iOS. Probably my xCode setting are wrong. It should work on iOS as well.

### CODE REVIEW

**Comment by akki-ng** [comment]
The dependency for Zoom works on iOS too. Check the render method of "index.ios.js" in PhotoBrowserZoomExample and set if condition to false to test "Zoom of image".

**Comment by musicode** [comment]
is it merged into master?

**Comment by halilb** [comment]
Hi @akki-ng! Thanks a lot for your time and contribution. I'm so sorry I couldn't take a look at this earlier.

The PR seems huge though. Is it possible for you to create a new PR with squashed commits and without unnecessary changes for the zoom capability(.flowconfig file for example).

**Comment by akki-ng** [comment]
@halilb Sorry for delay. Got busy in work. I will create a new PR after doing minimal changes.

**Pull request closed without merging**
