### PR TITLE
Feature: displayTopBar

### PR DESCRIPTION
**Pull request by miclaus**
### (refs #17)

**Note** `renderTopBar`:

``` es6
<PhotoBrowser
  mediaList={media}
  displayNavArrows={displayNavArrows}
  displayActionButton={displayActionButton}
  startOnGrid={startOnGrid}
  useCircleProgress
  renderTopBar={false}
  onSelectionChanged={this.onSelectionChanged}
  onBack={navigator.pop}
/>
```

Custom Header / TopBar: 

screen shot 2016-09-06 at 21 25 39

Fullscreen and controls shown:

screen shot 2016-09-06 at 21 25 51

@halilb What do you think? :)

### CODE REVIEW

**Comment by miclaus** [comment]
I might have accidentally removed `itemPerRow`

**Comment by halilb** [comment]
Thanks for your contribution @miclaus! Optional TopBar sounds like something people would need.

I wonder if we can use `displayTopBar` state to achieve something similar.

* Take `displayTopBar` as a property
* Set initial `displayTopBar` state of the index component to `displayTopBar` props:

```
this.state = {
  displayTopBar: props.displayTopbar
};
```
* Prevent `_toggleTopBar` method displaying the top bar
```
_toggleTopBar(displayed: boolean) {
    if (this.props.displayTopBar) {
      this.setState({
        displayTopBar: displayed,
      });
    }
  }
```

What do you think?

**Comment by miclaus** [comment]
@halilb Thought of that at first, but then I wasn't sure in the `render` functions, since there already was a `displayTopBar` :))

Let me give it a try, sounds good!

**Comment by miclaus** [comment]
Is it just me, or is the picture further below?

screen shot 2016-09-06 at 22 09 52

**Comment by miclaus** [comment]
When I say semicolon i mean `,`

@halilb This should fix the above mentioned paddingTop problem.

**Comment by miclaus** [comment]
@halilb We then experienced a minor issue concerning the selection button in fullscreen mode, on iOS, because of the **+20px** of the native StatusBar. 

In our case the selection button would slightly disappear behind our own HeaderBar / TopBar.

We changed the default Photo component style `fullScreenSelectionIcon.top` to `80` it is looks fine again. However no Platform checking has been done, since it might also be needed for Android.

**This is not included in this PR**, but you can find it on my `develop` branch, which we are currently using: https://github.com/miclaus/react-native-photo-browser/tree/develop

**Comment by halilb** [comment]
I'm so sorry that it took too long to review this @miclaus . I'll pull the latest code and test it before merging asap.

**Comment by halilb** [comment]
@miclaus It looks like I've missed this and merged a later PR for `displayTopBar` property.

I'm sorry about my oversight. Closing this PR in favour of #30.

**Comment by miclaus** [comment]
@halilb no problem !

however, it doesn't seem that all the issues mentioned here, are also considered in #30.

**Comment by halilb** [comment]
You're right @miclaus. I think we might also create a `renderTopbar` prop to let the parent component render it's custom top bar. It may also return a null component if it doesn't need any top bar.

**Pull request closed without merging**
