### PR TITLE
Minor changes for Zoom

### PR DESCRIPTION
**Pull request by akki-ng**
This will support zoom of image. And ActivityIndicator has been added as AndroidProgressBar is deprecated. Readme.md changes can be ignored as they were meant for internal audience.

### CODE REVIEW

**Comment by 7kfpun** [comment]
Android only?

**Comment by akki-ng** [comment]
Yes, for android only. I've tested these changes on Android and it works fine.

**Comment by 7kfpun** [comment]
I tested on iOS, the images could not show.

**Comment by akki-ng** [comment]
Okay, I'll check these on iOS and do updates if needed. Meanwhile can you confirm it to work on Android as I did not find any issues for Android.

**[Tip]**

While installing this module we must install the below module too in MainApplication, Settings.gradle, Build.gradle too.

**https://www.npmjs.com/package/react-native-image-zoom**

**Comment by akki-ng** [comment]
Did you put necessary entries into the concerned files for **react-native-image-zoom** ?

**Comment by ksti** [comment]
I'v already added the supporting of zooming photo in this [PR](https://github.com/halilb/react-native-photo-browser/pull/20), it works with both Android and iOS. Although it hasn't been accepted yet. Why don't you try this?:)

**Comment by akki-ng** [comment]
@ksti Sure, I will try this soon. Thanks.

**Comment by akki-ng** [comment]
@ksti I've found an issue with this change. Please ignore the pull request for now.

**Comment by akki-ng** [comment]
Close as new pull request is being made.

**Pull request closed without merging**
